
development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bitstars_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bitstars_test
  pool: 5
  password:

staging:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bitstars_staging
  pool: 5
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: bitstars_production
  pool: 5
  password:
